players = {
"Michele Cerofolini": {"ruolo": "Portiere", "valore": 0.50},
"Marco Pissardo": {"ruolo": "Portiere", "valore": 0.25},
"Davide Marfella": {"ruolo": "Portiere", "valore": 0.05},
"Cas Odenthal": {"ruolo": "Difensore", "valore": 2.00},
"Giacomo Stabile": {"ruolo": "Difensore", "valore": 1.20},
"Dimitrios Nikolaou": {"ruolo": "Difensore", "valore": 1.00},
"Andrea Cistana": {"ruolo": "Difensore", "valore": 0.75},
"Valerio Mantovani": {"ruolo": "Difensore", "valore": 0.50},
"Raffaele Pucino": {"ruolo": "Difensore", "valore": 0.15},
"Mehdi Dorval": {"ruolo": "Difensore", "valore": 2.00},
"Riccardo Burgio": {"ruolo": "Difensore", "valore": 0.15},
"Lorenzo Dickmann": {"ruolo": "Difensore", "valore": 0.70},
"Moussa Man´e": {"ruolo": "Difensore", "valore": 0.35},
"Matthias Verreth": {"ruolo": "Centrocampista", "valore": 0.90},
"Ebrima Darboe": {"ruolo": "Centrocampista", "valore": 0.80},
"Federico Artioli": {"ruolo": "Centrocampista", "valore": 0.50},
"Riccardo Pagano": {"ruolo": "Centrocampista", "valore": 2.20},
"Matthias Braun¨oder": {"ruolo": "Centrocampista", "valore": 1.20},
"Giulio Maggiore": {"ruolo": "Centrocampista", "valore": 0.90},
"Daouda Traor´e": {"ruolo": "Centrocampista", "valore": 0.40},
"Tom´as Esteves": {"ruolo": "Centrocampista", "valore": 1.90},
"Giuseppe Sibilli": {"ruolo": "Centrocampista", "valore": 0.80},
"Kevin Piscopo": {"ruolo": "Centrocampista", "valore": 0.50},
"Nicol`o Cavuoti": {"ruolo": "Centrocampista", "valore": 0.40},
"Nicola Bellomo": {"ruolo": "Centrocampista", "valore": 0.10},
"Emanuele Rao": {"ruolo": "Attaccante", "valore": 3.20},
"Giacomo De Pieri": {"ruolo": "Attaccante", "valore": 1.50},
"Anthony Partipilo": {"ruolo": "Attaccante", "valore": 0.40},
"Gabriele Moncini": {"ruolo": "Attaccante", "valore": 0.80},
"Marvin Cuni": {"ruolo": "Attaccante", "valore": 0.80},
"Christian Gytkjaer": {"ruolo": "Attaccante", "valore": 0.40}
}